server.host=localhost
server.port=9000

database.url=jdbc:postgresql://db.upagdhbrgkkbkxadzsao.supabase.co:5432/postgres?sslmode=require&connectTimeout=10&socketTimeout=60
database.username=postgres
database.password=lethiminhnguyet
