spring.datasource.url=jdbc:postgresql://db.upagdhbrgkkbkxadzsao.supabase.co:5432/postgres?sslmode=require&connectTimeout=10&socketTimeout=60
spring.datasource.username=postgres
spring.datasource.password=lethiminhnguyet
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.mvc.static-path-pattern=/**
server.port=8081
app.seed-on-startup=false
