-- Supabase/PostgreSQL schema for the Java desktop client/server project.
-- Run this in Supabase SQL Editor, then start the Java server to seed the full
-- encrypted sample dataset through BCrypt + AES utilities.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'TEACHER', 'STUDENT', 'USER')),
    locked BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS sinh_vien (
    ma_sv VARCHAR(20) PRIMARY KEY,
    ho_ten VARCHAR(100) NOT NULL,
    lop VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    sdt VARCHAR(255),
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    tuition_paid BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS giang_vien (
    ma_gv VARCHAR(20) PRIMARY KEY,
    ho_ten VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    sdt VARCHAR(255),
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS mon_hoc (
    ma_mh VARCHAR(20) PRIMARY KEY,
    ten_mh VARCHAR(100) NOT NULL,
    so_tin_chi INT NOT NULL CHECK (so_tin_chi BETWEEN 1 AND 10)
);

CREATE TABLE IF NOT EXISTS lop_hoc_phan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_lhp VARCHAR(20) UNIQUE NOT NULL,
    phong_hoc VARCHAR(20),
    lich_hoc VARCHAR(50),
    si_so_toi_da INT DEFAULT 100,
    si_so_hien_tai INT DEFAULT 0,
    mon_hoc_ma_mh VARCHAR(20) REFERENCES mon_hoc(ma_mh) ON DELETE RESTRICT,
    giang_vien_ma_gv VARCHAR(20) REFERENCES giang_vien(ma_gv) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS dang_ky_hoc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sinh_vien_ma_sv VARCHAR(20) REFERENCES sinh_vien(ma_sv) ON DELETE CASCADE,
    lop_hoc_phan_id BIGINT REFERENCES lop_hoc_phan(id) ON DELETE CASCADE,
    UNIQUE (sinh_vien_ma_sv, lop_hoc_phan_id)
);

CREATE TABLE IF NOT EXISTS diem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sinh_vien_ma_sv VARCHAR(20) REFERENCES sinh_vien(ma_sv) ON DELETE CASCADE,
    lop_hoc_phan_id BIGINT REFERENCES lop_hoc_phan(id) ON DELETE CASCADE,
    diemqt DOUBLE PRECISION DEFAULT 0 CHECK (diemqt BETWEEN 0 AND 10),
    diem_thi DOUBLE PRECISION DEFAULT 0 CHECK (diem_thi BETWEEN 0 AND 10),
    diem_tong_ket DOUBLE PRECISION DEFAULT 0 CHECK (diem_tong_ket BETWEEN 0 AND 10),
    locked BOOLEAN DEFAULT FALSE,
    UNIQUE (sinh_vien_ma_sv, lop_hoc_phan_id)
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lop_hoc_phan_id BIGINT REFERENCES lop_hoc_phan(id) ON DELETE CASCADE,
    sinh_vien_ma_sv VARCHAR(20) REFERENCES sinh_vien(ma_sv) ON DELETE CASCADE,
    ngay_diem_danh DATE NOT NULL,
    co_mat BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS phan_hoi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sinh_vien_ma_sv VARCHAR(20) REFERENCES sinh_vien(ma_sv) ON DELETE CASCADE,
    tieu_de VARCHAR(255) NOT NULL,
    noi_dung TEXT,
    loai_don VARCHAR(50),
    ngay_gui TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    trang_thai VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS system_config (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_year VARCHAR(20),
    current_semester VARCHAR(10),
    tuition_per_credit DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    target_role VARCHAR(20),
    target_id VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(50),
    action VARCHAR(100),
    status VARCHAR(20),
    details TEXT
);

-- English compatibility views for the required report/table names.
CREATE OR REPLACE VIEW students AS SELECT * FROM sinh_vien;
CREATE OR REPLACE VIEW subjects AS SELECT * FROM mon_hoc;
CREATE OR REPLACE VIEW classes AS SELECT * FROM lop_hoc_phan;
CREATE OR REPLACE VIEW grades AS SELECT * FROM diem;

INSERT INTO users (username, password, email, role, locked)
VALUES
    ('admin', '$2a$10$jalIHTiSfFCl3GfMoA0Gau/KOsqs108YgYhOf3I1DQbLq9oOD0CUu', 'admin@school.com', 'ADMIN', FALSE),
    ('gv01', '$2a$10$jalIHTiSfFCl3GfMoA0Gau/KOsqs108YgYhOf3I1DQbLq9oOD0CUu', 'gv01@school.com', 'TEACHER', FALSE),
    ('sv01', '$2a$10$jalIHTiSfFCl3GfMoA0Gau/KOsqs108YgYhOf3I1DQbLq9oOD0CUu', 'sv01@school.com', 'STUDENT', FALSE)
ON CONFLICT (username) DO NOTHING;

INSERT INTO mon_hoc (ma_mh, ten_mh, so_tin_chi)
VALUES
    ('IT101', 'Object Oriented Programming with Java', 3),
    ('IT102', 'Web Technology', 3),
    ('IT103', 'Database Systems', 3),
    ('MA101', 'Calculus 1', 4)
ON CONFLICT (ma_mh) DO NOTHING;

INSERT INTO system_config (current_year, current_semester, tuition_per_credit)
SELECT '2025-2026', '1', 500000
WHERE NOT EXISTS (SELECT 1 FROM system_config);
