package com.example.dean12.desktop.network;

import com.example.dean12.model.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ServerDao {

    // --- CONNECTION MANAGER ---
    public static Connection getConnection() throws SQLException {
        String url = ConfigUtil.getProperty("database.url");
        try {
            if (url != null && url.contains("jdbc:h2:")) {
                Class.forName("org.h2.Driver");
            } else if (url != null && url.contains("jdbc:postgresql:")) {
                Class.forName("org.postgresql.Driver");
            } else {
                throw new SQLException("Unsupported database.url. Use jdbc:postgresql for Supabase or jdbc:h2 for local fallback.");
            }
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("Không tìm thấy driver cơ sở dữ liệu", e);
        }
        return DriverManager.getConnection(
            url,
            ConfigUtil.getProperty("database.username"),
            ConfigUtil.getProperty("database.password")
        );
    }

    // --- SYSTEM LOGGING helper ---
    public void logActivity(String username, String action, String status, String details) {
        String sql = "INSERT INTO system_logs (timestamp, username, action, status, details) VALUES (CURRENT_TIMESTAMP, ?, ?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, username != null ? username : "SYSTEM");
            ps.setString(2, action);
            ps.setString(3, status);
            ps.setString(4, details);
            ps.executeUpdate();
            
            // Also print to console
            System.out.printf("[LOG] %s | %s | %s | %s | %s\n", new java.util.Date(), username, action, status, details);
        } catch (SQLException e) {
            System.err.println("[Logging Error] " + e.getMessage());
        }
    }

    // --- DATABASE INITIALIZATION ---
    public void initializeDatabaseSchema() {
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {

            // 0. Ensure Tables Exist
            // Users
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS users (" +
                               "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "username VARCHAR(50) UNIQUE, " +
                               "password VARCHAR(255), " +
                               "email VARCHAR(100), " +
                               "role VARCHAR(20), " +
                               "locked BOOLEAN DEFAULT FALSE)");

            // SinhVien
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS sinh_vien (" +
                               "ma_sv VARCHAR(20) PRIMARY KEY, " +
                               "ho_ten VARCHAR(100), " +
                               "lop VARCHAR(20), " +
                               "email VARCHAR(255), " +
                               "sdt VARCHAR(255), " +
                               "user_id BIGINT, " +
                               "tuition_paid BOOLEAN DEFAULT FALSE, " +
                               "FOREIGN KEY (user_id) REFERENCES users(id))");

            // GiangVien
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS giang_vien (" +
                               "ma_gv VARCHAR(20) PRIMARY KEY, " +
                               "ho_ten VARCHAR(100), " +
                               "email VARCHAR(255), " +
                               "sdt VARCHAR(255), " +
                               "user_id BIGINT, " +
                               "FOREIGN KEY (user_id) REFERENCES users(id))");

            // MonHoc
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS mon_hoc (" +
                               "ma_mh VARCHAR(20) PRIMARY KEY, " +
                               "ten_mh VARCHAR(100), " +
                               "so_tin_chi INT)");

            // LopHocPhan
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS lop_hoc_phan (" +
                               "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "ma_lhp VARCHAR(20), " +
                               "phong_hoc VARCHAR(20), " +
                               "lich_hoc VARCHAR(50), " +
                               "si_so_toi_da INT DEFAULT 100, " +
                               "si_so_hien_tai INT DEFAULT 0, " +
                               "mon_hoc_ma_mh VARCHAR(20), " +
                               "giang_vien_ma_gv VARCHAR(20), " +
                               "FOREIGN KEY (mon_hoc_ma_mh) REFERENCES mon_hoc(ma_mh), " +
                               "FOREIGN KEY (giang_vien_ma_gv) REFERENCES giang_vien(ma_gv))");

            // DangKyHoc
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS dang_ky_hoc (" +
                               "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "sinh_vien_ma_sv VARCHAR(20), " +
                               "lop_hoc_phan_id BIGINT, " +
                               "FOREIGN KEY (sinh_vien_ma_sv) REFERENCES sinh_vien(ma_sv), " +
                               "FOREIGN KEY (lop_hoc_phan_id) REFERENCES lop_hoc_phan(id))");

            // Diem
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS diem (" +
                               "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "sinh_vien_ma_sv VARCHAR(20), " +
                               "lop_hoc_phan_id BIGINT, " +
                               "diemqt DOUBLE PRECISION DEFAULT 0, " +
                               "diem_thi DOUBLE PRECISION DEFAULT 0, " +
                               "diem_tong_ket DOUBLE PRECISION DEFAULT 0, " +
                               "locked BOOLEAN DEFAULT FALSE, " +
                               "FOREIGN KEY (sinh_vien_ma_sv) REFERENCES sinh_vien(ma_sv), " +
                               "FOREIGN KEY (lop_hoc_phan_id) REFERENCES lop_hoc_phan(id))");

            // Attendance
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS attendance (" +
                               "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "lop_hoc_phan_id BIGINT, " +
                               "sinh_vien_ma_sv VARCHAR(20), " +
                               "ngay_diem_danh DATE, " +
                               "co_mat BOOLEAN DEFAULT FALSE)");

            // PhanHoi
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS phan_hoi (" +
                               "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "sinh_vien_ma_sv VARCHAR(20), " +
                               "tieu_de VARCHAR(255), " +
                               "noi_dung TEXT, " +
                               "loai_don VARCHAR(50), " +
                               "ngay_gui TIMESTAMP, " +
                               "trang_thai VARCHAR(20))");

            // System Config
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS system_config (" +
                               "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "current_year VARCHAR(20), " +
                               "current_semester VARCHAR(10), " +
                               "tuition_per_credit DOUBLE PRECISION)");

            // Notifications
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS notifications (" +
                               "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "title VARCHAR(255), " +
                               "content TEXT, " +
                               "target_role VARCHAR(20), " +
                               "target_id VARCHAR(50), " +
                               "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            // Logs table
            stmt.executeUpdate("CREATE TABLE IF NOT EXISTS system_logs (" +
                               "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "timestamp TIMESTAMP, " +
                               "username VARCHAR(50), " +
                               "action VARCHAR(100), " +
                               "status VARCHAR(20), " +
                               "details TEXT)");

            ensureUsersTableColumns(conn);

            stmt.executeUpdate("INSERT INTO system_config (current_year, current_semester, tuition_per_credit) " +
                               "SELECT '2025-2026', '1', 500000 WHERE NOT EXISTS (SELECT * FROM system_config)");

            System.out.println("[Server Schema] Database schema ready.");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /** Thêm cột locked nếu bảng users đã được tạo trước đó bởi JPA. */
    private void ensureUsersTableColumns(Connection conn) {
        try (Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("ALTER TABLE users ADD COLUMN IF NOT EXISTS locked BOOLEAN DEFAULT FALSE");
        } catch (SQLException e) {
            System.err.println("[Server Schema] Không thể thêm cột locked: " + e.getMessage());
        }
    }

    private long findUserId(Connection conn, String username) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("SELECT id FROM users WHERE username = ?")) {
            ps.setString(1, username);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getLong(1);
                }
            }
        }
        return -1;
    }

    // --- SYSTEM CONFIG ---
    public void updateSystemConfig(String year, String semester, double tuition) {
        String sql = "UPDATE system_config SET current_year = ?, current_semester = ?, tuition_per_credit = ? WHERE id = 1";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, year);
            ps.setString(2, semester);
            ps.setDouble(3, tuition);
            ps.executeUpdate();
            logActivity("SYSTEM", "UPDATE_SYSTEM_CONFIG", "SUCCESS", "Semester: " + semester + ", Year: " + year);
        } catch (SQLException e) {
            logActivity("SYSTEM", "UPDATE_SYSTEM_CONFIG", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public String[] getSystemConfig() {
        String sql = "SELECT * FROM system_config LIMIT 1";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return new String[]{
                    rs.getString("current_year"),
                    rs.getString("current_semester"),
                    String.valueOf(rs.getDouble("tuition_per_credit"))
                };
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return new String[]{"2025-2026", "1", "500000"};
    }

    // --- NOTIFICATIONS ---
    public void createNotification(String title, String content, String role, String targetId) {
        String sql = "INSERT INTO notifications (title, content, target_role, target_id) VALUES (?, ?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, title);
            ps.setString(2, content);
            ps.setString(3, role);
            ps.setString(4, targetId);
            ps.executeUpdate();
            logActivity("SYSTEM", "CREATE_NOTIFICATION", "SUCCESS", "Title: " + title + ", Role: " + role);
        } catch (SQLException e) {
            logActivity("SYSTEM", "CREATE_NOTIFICATION", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void createNotification(String title, String content, String role) {
        createNotification(title, content, role, "");
    }

    public List<ThongBao> getAllNotifications() {
        List<ThongBao> list = new ArrayList<>();
        String sql = "SELECT * FROM notifications ORDER BY created_at DESC";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                ThongBao tb = new ThongBao();
                tb.setId(rs.getLong("id"));
                tb.setTieuDe(rs.getString("title"));
                tb.setNoiDung(rs.getString("content"));
                tb.setDoiTuong(rs.getString("target_role"));
                Timestamp ts = rs.getTimestamp("created_at");
                if (ts != null) tb.setNgayTao(ts.toLocalDateTime());
                list.add(tb);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public List<String[]> getNotifications(String role, String classId) {
        List<String[]> list = new ArrayList<>();
        String sql = "SELECT * FROM notifications WHERE target_role = 'ALL' OR target_role = ? OR (target_role = 'CLASS' AND target_id = ?) ORDER BY created_at DESC";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, role);
            ps.setString(2, classId != null ? classId : "");
            try (ResultSet rs = ps.executeQuery()) {
                while(rs.next()) {
                    list.add(new String[]{
                        rs.getString("title"),
                        rs.getString("content"),
                        rs.getString("created_at")
                    });
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    // --- TUITION ---
    public void payTuition(String maSV) {
         String sql = "UPDATE sinh_vien SET tuition_paid = TRUE WHERE ma_sv = ?";
         try (Connection conn = getConnection();
              PreparedStatement ps = conn.prepareStatement(sql)) {
             ps.setString(1, maSV);
             ps.executeUpdate();
             logActivity(maSV, "PAY_TUITION", "SUCCESS", "Student: " + maSV);
         } catch (SQLException e) {
             logActivity(maSV, "PAY_TUITION", "FAIL", e.getMessage());
             e.printStackTrace();
         }
    }

    // --- USER / AUTH ---
    public User login(String username, String password) {
        if (username == null || password == null) {
            return null;
        }
        username = username.trim();
        password = password.trim();

        String sql = "SELECT * FROM users WHERE username = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, username);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    System.out.println("[Login] Không tìm thấy user: " + username);
                    return null;
                }
                if (readLocked(rs)) {
                    System.out.println("[Login] Tài khoản bị khóa: " + username);
                    return null;
                }
                String dbPass = rs.getString("password");
                if (!com.example.dean12.desktop.PasswordUtil.matches(password, dbPass)) {
                    System.out.println("[Login] Sai mật khẩu: " + username);
                    return null;
                }
                User u = new User();
                u.setId(rs.getLong("id"));
                u.setUsername(rs.getString("username"));
                u.setPassword(dbPass);
                u.setEmail(rs.getString("email"));
                u.setRole(rs.getString("role"));
                u.setLocked(false);
                System.out.println("[Login] Thành công: " + username + " (" + u.getRole() + ")");
                return u;
            }
        } catch (SQLException e) {
            System.err.println("[Login] Lỗi SQL: " + e.getMessage());
            e.printStackTrace();
        }
        return null;
    }

    private boolean readLocked(ResultSet rs) {
        try {
            return rs.getBoolean("locked");
        } catch (SQLException e) {
            return false;
        }
    }

    // --- ADMIN: MANAGE STUDENTS ---
    public List<SinhVien> getAllStudents() {
        List<SinhVien> list = new ArrayList<>();
        String sql = "SELECT * FROM sinh_vien";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                SinhVien sv = new SinhVien();
                sv.setMaSV(rs.getString("ma_sv"));
                sv.setHoTen(rs.getString("ho_ten"));
                sv.setLop(rs.getString("lop"));
                // AES Decryption
                sv.setEmail(AesUtil.decrypt(rs.getString("email")));
                sv.setSdt(AesUtil.decrypt(rs.getString("sdt")));
                sv.setTuitionPaid(rs.getBoolean("tuition_paid"));
                list.add(sv);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public void createStudent(SinhVien sv, String username, String password) {
        String sqlUser = "INSERT INTO users (username, password, email, role) VALUES (?, ?, ?, 'STUDENT')";
        String sqlSV = "INSERT INTO sinh_vien (ma_sv, ho_ten, lop, email, sdt, user_id) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = getConnection()) {
            conn.setAutoCommit(false);
            try {
                // 1. Create User
                long userId = -1;
                try (PreparedStatement psUser = conn.prepareStatement(sqlUser, Statement.RETURN_GENERATED_KEYS)) {
                    psUser.setString(1, username);
                    psUser.setString(2, com.example.dean12.desktop.PasswordUtil.encode(password));
                    psUser.setString(3, sv.getEmail()); // plain text email for spring security web UI if needed
                    psUser.executeUpdate();
                    try (ResultSet rs = psUser.getGeneratedKeys()) {
                        if (rs.next()) userId = rs.getLong(1);
                    }
                }

                if (userId == -1) throw new SQLException("Failed to create user");

                // 2. Create SinhVien (Sensitive fields AES encrypted)
                try (PreparedStatement psSV = conn.prepareStatement(sqlSV)) {
                    psSV.setString(1, sv.getMaSV());
                    psSV.setString(2, sv.getHoTen());
                    psSV.setString(3, sv.getLop());
                    psSV.setString(4, AesUtil.encrypt(sv.getEmail()));
                    psSV.setString(5, AesUtil.encrypt(sv.getSdt()));
                    psSV.setLong(6, userId);
                    psSV.executeUpdate();
                }

                conn.commit();
                logActivity("ADMIN", "CREATE_STUDENT", "SUCCESS", "maSV: " + sv.getMaSV());
            } catch (SQLException e) {
                conn.rollback();
                logActivity("ADMIN", "CREATE_STUDENT", "FAIL", e.getMessage());
                throw e;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void updateStudent(String maSV, String hoTen, String lop, String email, String sdt) {
        String sql = "UPDATE sinh_vien SET ho_ten = ?, lop = ?, email = ?, sdt = ? WHERE ma_sv = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, hoTen);
            ps.setString(2, lop);
            ps.setString(3, AesUtil.encrypt(email)); // AES Encrypt
            ps.setString(4, AesUtil.encrypt(sdt));   // AES Encrypt
            ps.setString(5, maSV);
            ps.executeUpdate();
            logActivity("ADMIN", "UPDATE_STUDENT", "SUCCESS", "maSV: " + maSV);
        } catch (SQLException e) {
            logActivity("ADMIN", "UPDATE_STUDENT", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void deleteStudent(String maSV) {
        try (Connection conn = getConnection()) {
            conn.setAutoCommit(false);
            try {
                // Get user_id first
                long userId = -1;
                try (PreparedStatement ps = conn.prepareStatement("SELECT user_id FROM sinh_vien WHERE ma_sv = ?")) {
                    ps.setString(1, maSV);
                    try (ResultSet rs = ps.executeQuery()) {
                        if (rs.next()) userId = rs.getLong(1);
                    }
                }

                // Delete related records (Transaction ensures atomic delete)
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM diem WHERE sinh_vien_ma_sv = ?")) {
                    ps.setString(1, maSV);
                    ps.executeUpdate();
                }
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM dang_ky_hoc WHERE sinh_vien_ma_sv = ?")) {
                    ps.setString(1, maSV);
                    ps.executeUpdate();
                }
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM attendance WHERE sinh_vien_ma_sv = ?")) {
                    ps.setString(1, maSV);
                    ps.executeUpdate();
                }
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM phan_hoi WHERE sinh_vien_ma_sv = ?")) {
                    ps.setString(1, maSV);
                    ps.executeUpdate();
                }
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM sinh_vien WHERE ma_sv = ?")) {
                    ps.setString(1, maSV);
                    ps.executeUpdate();
                }

                // Delete user
                if (userId != -1) {
                    try (PreparedStatement ps = conn.prepareStatement("DELETE FROM users WHERE id = ?")) {
                        ps.setLong(1, userId);
                        ps.executeUpdate();
                    }
                }

                conn.commit();
                logActivity("ADMIN", "DELETE_STUDENT", "SUCCESS", "maSV: " + maSV);
            } catch (SQLException ex) {
                conn.rollback();
                logActivity("ADMIN", "DELETE_STUDENT", "FAIL", ex.getMessage());
                throw ex;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // --- ADMIN: MANAGE COURSES ---
    public List<MonHoc> getAllCourses() {
        List<MonHoc> list = new ArrayList<>();
        String sql = "SELECT * FROM mon_hoc";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                MonHoc mh = new MonHoc();
                mh.setMaMH(rs.getString("ma_mh"));
                mh.setTenMH(rs.getString("ten_mh"));
                mh.setSoTinChi(rs.getInt("so_tin_chi"));
                list.add(mh);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public void createCourse(MonHoc mh) {
        String sql = "INSERT INTO mon_hoc (ma_mh, ten_mh, so_tin_chi) VALUES (?, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, mh.getMaMH());
            ps.setString(2, mh.getTenMH());
            ps.setInt(3, mh.getSoTinChi());
            ps.executeUpdate();
            logActivity("ADMIN", "CREATE_COURSE", "SUCCESS", "maMH: " + mh.getMaMH());
        } catch (SQLException e) {
            logActivity("ADMIN", "CREATE_COURSE", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void updateCourse(String maMH, String tenMH, int soTinChi) {
        String sql = "UPDATE mon_hoc SET ten_mh = ?, so_tin_chi = ? WHERE ma_mh = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, tenMH);
            ps.setInt(2, soTinChi);
            ps.setString(3, maMH);
            ps.executeUpdate();
            logActivity("ADMIN", "UPDATE_COURSE", "SUCCESS", "maMH: " + maMH);
        } catch (SQLException e) {
            logActivity("ADMIN", "UPDATE_COURSE", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void deleteCourse(String maMH) {
        String sql = "DELETE FROM mon_hoc WHERE ma_mh = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, maMH);
            ps.executeUpdate();
            logActivity("ADMIN", "DELETE_COURSE", "SUCCESS", "maMH: " + maMH);
        } catch (SQLException e) {
            logActivity("ADMIN", "DELETE_COURSE", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    // --- ADMIN: MANAGE CLASSES (LopHocPhan) ---
    public List<LopHocPhan> getAllClasses() {
        List<LopHocPhan> list = new ArrayList<>();
        String sql = "SELECT l.*, m.ten_mh, g.ho_ten as gv_ten FROM lop_hoc_phan l " +
                     "LEFT JOIN mon_hoc m ON l.mon_hoc_ma_mh = m.ma_mh " +
                     "LEFT JOIN giang_vien g ON l.giang_vien_ma_gv = g.ma_gv";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                LopHocPhan lhp = new LopHocPhan();
                lhp.setId(rs.getLong("id"));
                lhp.setMaLhp(rs.getString("ma_lhp"));
                lhp.setPhongHoc(rs.getString("phong_hoc"));
                lhp.setLichHoc(rs.getString("lich_hoc"));
                lhp.setSiSoHienTai(rs.getInt("si_so_hien_tai"));
                lhp.setSiSoToiDa(rs.getInt("si_so_toi_da"));

                MonHoc mh = new MonHoc();
                mh.setMaMH(rs.getString("mon_hoc_ma_mh"));
                mh.setTenMH(rs.getString("ten_mh"));
                lhp.setMonHoc(mh);

                if (rs.getString("giang_vien_ma_gv") != null) {
                    GiangVien gv = new GiangVien();
                    gv.setMaGV(rs.getString("giang_vien_ma_gv"));
                    gv.setHoTen(rs.getString("gv_ten"));
                    lhp.setGiangVien(gv);
                } else {
                    GiangVien gvTrong = new GiangVien();
                    gvTrong.setHoTen("Chưa phân công");
                    lhp.setGiangVien(gvTrong);
                }

                list.add(lhp);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public void createClass(LopHocPhan lhp) {
        String sql = "INSERT INTO lop_hoc_phan (ma_lhp, phong_hoc, lich_hoc, si_so_toi_da, si_so_hien_tai, mon_hoc_ma_mh, giang_vien_ma_gv) " +
                     "VALUES (?, ?, ?, 100, 0, ?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, lhp.getMaLhp());
            ps.setString(2, lhp.getPhongHoc());
            ps.setString(3, lhp.getLichHoc());
            ps.setString(4, lhp.getMonHoc().getMaMH());

            if (lhp.getGiangVien() != null && !lhp.getGiangVien().getMaGV().isEmpty()) {
                ps.setString(5, lhp.getGiangVien().getMaGV());
            } else {
                ps.setNull(5, Types.VARCHAR);
            }

            ps.executeUpdate();
            logActivity("ADMIN", "CREATE_CLASS", "SUCCESS", "maLHP: " + lhp.getMaLhp());
        } catch (SQLException e) {
            logActivity("ADMIN", "CREATE_CLASS", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void updateClass(Long id, String maLhp, String phongHoc, String lichHoc, String maGV) {
        String sql = "UPDATE lop_hoc_phan SET ma_lhp = ?, phong_hoc = ?, lich_hoc = ?, giang_vien_ma_gv = ? WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, maLhp);
            ps.setString(2, phongHoc);
            ps.setString(3, lichHoc);
            if (maGV != null && !maGV.isEmpty()) {
                ps.setString(4, maGV);
            } else {
                ps.setNull(4, Types.VARCHAR);
            }
            ps.setLong(5, id);
            ps.executeUpdate();
            logActivity("ADMIN", "UPDATE_CLASS", "SUCCESS", "classId: " + id);
        } catch (SQLException e) {
            logActivity("ADMIN", "UPDATE_CLASS", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void deleteClass(Long id) {
        try (Connection conn = getConnection()) {
            conn.setAutoCommit(false);
            try {
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM diem WHERE lop_hoc_phan_id = ?")) {
                    ps.setLong(1, id);
                    ps.executeUpdate();
                }
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM dang_ky_hoc WHERE lop_hoc_phan_id = ?")) {
                    ps.setLong(1, id);
                    ps.executeUpdate();
                }
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM attendance WHERE lop_hoc_phan_id = ?")) {
                    ps.setLong(1, id);
                    ps.executeUpdate();
                }
                try (PreparedStatement ps = conn.prepareStatement("DELETE FROM lop_hoc_phan WHERE id = ?")) {
                    ps.setLong(1, id);
                    ps.executeUpdate();
                }
                conn.commit();
                logActivity("ADMIN", "DELETE_CLASS", "SUCCESS", "classId: " + id);
            } catch (SQLException ex) {
                conn.rollback();
                logActivity("ADMIN", "DELETE_CLASS", "FAIL", ex.getMessage());
                throw ex;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public List<GiangVien> getAllTeachers() {
        List<GiangVien> list = new ArrayList<>();
        String sql = "SELECT * FROM giang_vien";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                GiangVien gv = new GiangVien();
                gv.setMaGV(rs.getString("ma_gv"));
                gv.setHoTen(rs.getString("ho_ten"));
                gv.setEmail(AesUtil.decrypt(rs.getString("email")));
                gv.setSdt(AesUtil.decrypt(rs.getString("sdt")));
                list.add(gv);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    // --- TEACHER METHODS ---
    public List<LopHocPhan> getClassesByTeacher(String maGV) {
        List<LopHocPhan> list = new ArrayList<>();
        String sql = "SELECT l.*, m.ten_mh, m.ma_mh FROM lop_hoc_phan l " +
                     "JOIN mon_hoc m ON l.mon_hoc_ma_mh = m.ma_mh " +
                     "WHERE l.giang_vien_ma_gv = ? ORDER BY l.ma_lhp";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, maGV);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    LopHocPhan lhp = new LopHocPhan();
                    lhp.setId(rs.getLong("id"));
                    lhp.setMaLhp(rs.getString("ma_lhp"));
                    lhp.setPhongHoc(rs.getString("phong_hoc"));
                    lhp.setLichHoc(rs.getString("lich_hoc"));

                    MonHoc mh = new MonHoc();
                    mh.setMaMH(rs.getString("ma_mh"));
                    mh.setTenMH(rs.getString("ten_mh"));
                    lhp.setMonHoc(mh);
                    lhp.setSiSoHienTai(rs.getInt("si_so_hien_tai"));
                    lhp.setSiSoToiDa(rs.getInt("si_so_toi_da"));
                    list.add(lhp);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public List<DangKyHoc> getStudentsInClass(Long lhpId) {
        List<DangKyHoc> list = new ArrayList<>();
        String sql = "SELECT dk.*, sv.ma_sv, sv.ho_ten, sv.lop FROM dang_ky_hoc dk " +
                     "JOIN sinh_vien sv ON dk.sinh_vien_ma_sv = sv.ma_sv " +
                     "WHERE dk.lop_hoc_phan_id = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setLong(1, lhpId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    DangKyHoc dk = new DangKyHoc();
                    dk.setId(rs.getLong("id"));

                    SinhVien sv = new SinhVien();
                    sv.setMaSV(rs.getString("ma_sv"));
                    sv.setHoTen(rs.getString("ho_ten"));
                    sv.setLop(rs.getString("lop"));
                    dk.setSinhVien(sv);

                    list.add(dk);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public void saveAttendance(Long lhpId, String maSV, Date date, boolean present) {
        String sqlCheck = "SELECT id FROM attendance WHERE lop_hoc_phan_id = ? AND sinh_vien_ma_sv = ? AND ngay_diem_danh = ?";
        String sqlInsert = "INSERT INTO attendance (lop_hoc_phan_id, sinh_vien_ma_sv, ngay_diem_danh, co_mat) VALUES (?, ?, ?, ?)";
        String sqlUpdate = "UPDATE attendance SET co_mat = ? WHERE id = ?";

        try (Connection conn = getConnection()) {
            Long existId = null;
            try (PreparedStatement ps = conn.prepareStatement(sqlCheck)) {
                ps.setLong(1, lhpId);
                ps.setString(2, maSV);
                ps.setDate(3, date);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) existId = rs.getLong(1);
                }
            }

            if (existId == null) {
                try (PreparedStatement ps = conn.prepareStatement(sqlInsert)) {
                    ps.setLong(1, lhpId);
                    ps.setString(2, maSV);
                    ps.setDate(3, date);
                    ps.setBoolean(4, present);
                    ps.executeUpdate();
                }
            } else {
                try (PreparedStatement ps = conn.prepareStatement(sqlUpdate)) {
                    ps.setBoolean(1, present);
                    ps.setLong(2, existId);
                    ps.executeUpdate();
                }
            }
            logActivity("TEACHER", "SAVE_ATTENDANCE", "SUCCESS", "Student: " + maSV + ", Present: " + present);
        } catch (SQLException e) {
            logActivity("TEACHER", "SAVE_ATTENDANCE", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public List<Diem> getGradesByClass(Long lhpId) {
        List<Diem> list = new ArrayList<>();
        ensureGrades(lhpId);

        String sql = "SELECT d.*, sv.ho_ten, sv.ma_sv AS student_ma_sv, m.ten_mh, m.so_tin_chi, l.ma_lhp " +
                     "FROM diem d JOIN sinh_vien sv ON d.sinh_vien_ma_sv = sv.ma_sv " +
                     "JOIN lop_hoc_phan l ON d.lop_hoc_phan_id = l.id " +
                     "JOIN mon_hoc m ON l.mon_hoc_ma_mh = m.ma_mh WHERE d.lop_hoc_phan_id = ? ORDER BY sv.ma_sv";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setLong(1, lhpId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    Diem d = mapDiemRow(rs);
                    list.add(d);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    private void ensureGrades(Long lhpId) {
        String sqlMissing = "SELECT dk.sinh_vien_ma_sv FROM dang_ky_hoc dk " +
                             "LEFT JOIN diem d ON dk.sinh_vien_ma_sv = d.sinh_vien_ma_sv AND d.lop_hoc_phan_id = dk.lop_hoc_phan_id " +
                             "WHERE dk.lop_hoc_phan_id = ? AND d.id IS NULL";
        String sqlInsert = "INSERT INTO diem (sinh_vien_ma_sv, lop_hoc_phan_id, diemqt, diem_thi, locked) VALUES (?, ?, 0, 0, false)";

        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sqlMissing)) {
            ps.setLong(1, lhpId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    String maSV = rs.getString(1);
                    try (PreparedStatement pi = conn.prepareStatement(sqlInsert)) {
                        pi.setString(1, maSV);
                        pi.setLong(2, lhpId);
                        pi.executeUpdate();
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void updateGrade(Diem d) {
        String sql = "UPDATE diem SET diemqt = ?, diem_thi = ?, diem_tong_ket = ? WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setDouble(1, d.getDiemQT());
            ps.setDouble(2, d.getDiemThi());
            ps.setDouble(3, d.getDiemTongKet());
            ps.setLong(4, d.getId());
            ps.executeUpdate();
            logActivity("TEACHER", "UPDATE_GRADE", "SUCCESS", "GradeId: " + d.getId() + ", Final: " + d.getDiemTongKet());
        } catch (SQLException e) {
            logActivity("TEACHER", "UPDATE_GRADE", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void lockGrades(Long lhpId) {
        String sql = "UPDATE diem SET locked = true WHERE lop_hoc_phan_id = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setLong(1, lhpId);
            ps.executeUpdate();
            logActivity("TEACHER", "LOCK_GRADES", "SUCCESS", "classId: " + lhpId);
        } catch (SQLException e) {
            logActivity("TEACHER", "LOCK_GRADES", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    // --- STUDENT METHODS ---
    public SinhVien getStudentByUsername(String username) {
        String sql = "SELECT sv.* FROM sinh_vien sv JOIN users u ON sv.user_id = u.id WHERE u.username = ?";
        String sql2 = "SELECT * FROM sinh_vien WHERE UPPER(ma_sv) = UPPER(?)";

        try (Connection conn = getConnection()) {
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, username);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        return mapStudent(rs);
                    }
                }
            }
            try (PreparedStatement ps = conn.prepareStatement(sql2)) {
                ps.setString(1, username);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        return mapStudent(rs);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    public SinhVien getStudentByProperties(String maSV) {
        String sql = "SELECT * FROM sinh_vien WHERE ma_sv = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, maSV);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return mapStudent(rs);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    public String[] getTuitionInfo(String maSV) {
        int credits = countRegisteredCredits(maSV);
        double rate = getTuitionPerCredit();
        double total = credits * rate;
        SinhVien sv = getStudentByProperties(maSV);
        boolean paid = sv != null && sv.isTuitionPaid();
        return new String[]{
                String.valueOf(credits),
                String.valueOf((long) rate),
                String.valueOf((long) total),
                paid ? "true" : "false"
        };
    }

    private int countRegisteredCredits(String maSV) {
        String sql = "SELECT COALESCE(SUM(m.so_tin_chi), 0) FROM dang_ky_hoc dk " +
                     "JOIN lop_hoc_phan l ON dk.lop_hoc_phan_id = l.id " +
                     "JOIN mon_hoc m ON l.mon_hoc_ma_mh = m.ma_mh WHERE dk.sinh_vien_ma_sv = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, maSV);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

    private double getTuitionPerCredit() {
        String[] cfg = getSystemConfig();
        try {
            return Double.parseDouble(cfg[2]);
        } catch (Exception e) {
            return 500000;
        }
    }

    private SinhVien mapStudent(ResultSet rs) throws SQLException {
        SinhVien sv = new SinhVien();
        sv.setMaSV(rs.getString("ma_sv"));
        sv.setHoTen(rs.getString("ho_ten"));
        sv.setLop(rs.getString("lop"));
        sv.setEmail(AesUtil.decrypt(rs.getString("email")));
        sv.setSdt(AesUtil.decrypt(rs.getString("sdt")));
        try {
            sv.setTuitionPaid(rs.getBoolean("tuition_paid"));
        } catch (SQLException ignored) {
            sv.setTuitionPaid(false);
        }
        return sv;
    }

    public List<DangKyHoc> getStudentSchedule(String maSV) {
        List<DangKyHoc> list = new ArrayList<>();
        String sql = "SELECT dk.*, l.ma_lhp, l.phong_hoc, l.lich_hoc, m.ten_mh, g.ho_ten as gv_ten " +
                     "FROM dang_ky_hoc dk " +
                     "JOIN lop_hoc_phan l ON dk.lop_hoc_phan_id = l.id " +
                     "JOIN mon_hoc m ON l.mon_hoc_ma_mh = m.ma_mh " +
                     "LEFT JOIN giang_vien g ON l.giang_vien_ma_gv = g.ma_gv " +
                     "WHERE dk.sinh_vien_ma_sv = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, maSV);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    DangKyHoc dk = new DangKyHoc();
                    dk.setId(rs.getLong("id"));

                    LopHocPhan lhp = new LopHocPhan();
                    lhp.setMaLhp(rs.getString("ma_lhp"));
                    lhp.setPhongHoc(rs.getString("phong_hoc"));
                    lhp.setLichHoc(rs.getString("lich_hoc"));

                    MonHoc mh = new MonHoc();
                    mh.setTenMH(rs.getString("ten_mh"));
                    lhp.setMonHoc(mh);

                    GiangVien gv = new GiangVien();
                    gv.setHoTen(rs.getString("gv_ten"));
                    lhp.setGiangVien(gv);

                    dk.setLopHocPhan(lhp);
                    list.add(dk);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public GiangVien getTeacherByUsername(String username) {
        String sql = "SELECT g.* FROM giang_vien g JOIN users u ON g.user_id = u.id WHERE u.username = ?";
        String sql2 = "SELECT * FROM giang_vien WHERE ma_gv = ?";

        try (Connection conn = getConnection()) {
             try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, username);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        GiangVien g = new GiangVien();
                        g.setMaGV(rs.getString("ma_gv"));
                        g.setHoTen(rs.getString("ho_ten"));
                        g.setEmail(AesUtil.decrypt(rs.getString("email")));
                        g.setSdt(AesUtil.decrypt(rs.getString("sdt")));
                        return g;
                    }
                }
             }
             try (PreparedStatement ps = conn.prepareStatement(sql2)) {
                ps.setString(1, username);
                try (ResultSet rs = ps.executeQuery()) {
                     if (rs.next()) {
                        GiangVien g = new GiangVien();
                        g.setMaGV(rs.getString("ma_gv"));
                        g.setHoTen(rs.getString("ho_ten"));
                        g.setEmail(AesUtil.decrypt(rs.getString("email")));
                        g.setSdt(AesUtil.decrypt(rs.getString("sdt")));
                        return g;
                    }
                }
             }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    public void updateTeacherProfile(String maGV, String email, String sdt) {
        String sql = "UPDATE giang_vien SET email = ?, sdt = ? WHERE ma_gv = ?";
         try (Connection conn = getConnection();
              PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, AesUtil.encrypt(email));
            ps.setString(2, AesUtil.encrypt(sdt));
            ps.setString(3, maGV);
            ps.executeUpdate();
            logActivity(maGV, "UPDATE_TEACHER_PROFILE", "SUCCESS", "Teacher Profile Updated: " + maGV);
        } catch (SQLException e) {
            logActivity(maGV, "UPDATE_TEACHER_PROFILE", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void updateStudentProfile(String maSV, String email, String sdt) {
        String sql = "UPDATE sinh_vien SET email = ?, sdt = ? WHERE ma_sv = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, AesUtil.encrypt(email));
            ps.setString(2, AesUtil.encrypt(sdt));
            ps.setString(3, maSV);
            ps.executeUpdate();
            logActivity(maSV, "UPDATE_STUDENT_PROFILE", "SUCCESS", "Student Profile Updated: " + maSV);
        } catch (SQLException e) {
            logActivity(maSV, "UPDATE_STUDENT_PROFILE", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public List<LopHocPhan> getAvailableClassesForRegistration(String search) {
        List<LopHocPhan> list = new ArrayList<>();
        String sql = "SELECT l.*, m.ten_mh, m.so_tin_chi, g.ho_ten as gv_ten FROM lop_hoc_phan l " +
                     "JOIN mon_hoc m ON l.mon_hoc_ma_mh = m.ma_mh " +
                     "LEFT JOIN giang_vien g ON l.giang_vien_ma_gv = g.ma_gv " +
                     "WHERE l.mon_hoc_ma_mh LIKE ? OR m.ten_mh LIKE ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            String q = "%" + search + "%";
            ps.setString(1, q);
            ps.setString(2, q);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    LopHocPhan lhp = new LopHocPhan();
                    lhp.setId(rs.getLong("id"));
                    lhp.setMaLhp(rs.getString("ma_lhp"));
                    lhp.setPhongHoc(rs.getString("phong_hoc"));
                    lhp.setLichHoc(rs.getString("lich_hoc"));
                    lhp.setSiSoHienTai(rs.getInt("si_so_hien_tai"));
                    lhp.setSiSoToiDa(rs.getInt("si_so_toi_da"));

                    MonHoc mh = new MonHoc();
                    mh.setTenMH(rs.getString("ten_mh"));
                    mh.setSoTinChi(rs.getInt("so_tin_chi"));
                    lhp.setMonHoc(mh);

                    GiangVien gv = new GiangVien();
                    gv.setHoTen(rs.getString("gv_ten"));
                    lhp.setGiangVien(gv);

                    list.add(lhp);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public String registerClass(String maSV, Long lhpId) {
        SinhVien svInfo = getStudentByProperties(maSV);
        if (svInfo != null && !svInfo.isTuitionPaid()) {
            return "Vui lòng đóng học phí kỳ học hiện tại trước khi đăng ký thêm lớp!";
        }

        String sqlCheck = "SELECT id FROM dang_ky_hoc WHERE sinh_vien_ma_sv = ? AND lop_hoc_phan_id = ?";
        String sqlCap = "SELECT si_so_hien_tai, si_so_toi_da FROM lop_hoc_phan WHERE id = ?";
        String sqlReg = "INSERT INTO dang_ky_hoc (sinh_vien_ma_sv, lop_hoc_phan_id) VALUES (?, ?)";
        String sqlUpd = "UPDATE lop_hoc_phan SET si_so_hien_tai = si_so_hien_tai + 1 WHERE id = ?";

        try (Connection conn = getConnection()) {
            try (PreparedStatement ps = conn.prepareStatement(sqlCheck)) {
                ps.setString(1, maSV);
                ps.setLong(2, lhpId);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) return "Bạn đã đăng ký lớp này rồi!";
                }
            }
            try (PreparedStatement ps = conn.prepareStatement(sqlCap)) {
                ps.setLong(1, lhpId);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        if (rs.getInt(1) >= rs.getInt(2)) return "Lớp đã đầy!";
                    } else return "Lớp không tồn tại!";
                }
            }
            conn.setAutoCommit(false);
            try {
                try (PreparedStatement ps = conn.prepareStatement(sqlReg)) {
                    ps.setString(1, maSV);
                    ps.setLong(2, lhpId);
                    ps.executeUpdate();
                }
                try (PreparedStatement ps = conn.prepareStatement(sqlUpd)) {
                    ps.setLong(1, lhpId);
                    ps.executeUpdate();
                }
                conn.commit();
                logActivity(maSV, "REGISTER_CLASS", "SUCCESS", "classId: " + lhpId);
                return "Đăng ký thành công!";
            } catch (SQLException ex) {
                conn.rollback();
                logActivity(maSV, "REGISTER_CLASS", "FAIL", ex.getMessage());
                throw ex;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return "Lỗi Server: " + e.getMessage();
        }
    }

    // --- ADMIN: USER ACCOUNT MANAGEMENT ---
    public void createUserAccount(String username, String password, String email, String role) {
        String sql = "INSERT INTO users (username, password, email, role, locked) VALUES (?, ?, ?, ?, FALSE)";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, username);
            ps.setString(2, com.example.dean12.desktop.PasswordUtil.encode(password));
            ps.setString(3, email);
            ps.setString(4, role);
            ps.executeUpdate();
            logActivity("ADMIN", "CREATE_USER", "SUCCESS", "Username: " + username + ", Role: " + role);
        } catch (SQLException e) {
            logActivity("ADMIN", "CREATE_USER", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void deleteUserAccount(String username) {
        String sql = "DELETE FROM users WHERE username = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, username);
            ps.executeUpdate();
            logActivity("ADMIN", "DELETE_USER", "SUCCESS", "Username: " + username);
        } catch (SQLException e) {
            logActivity("ADMIN", "DELETE_USER", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void lockUserAccount(String username) {
        String sql = "UPDATE users SET locked = TRUE WHERE username = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, username);
            ps.executeUpdate();
            logActivity("ADMIN", "LOCK_USER", "SUCCESS", "Username: " + username);
        } catch (SQLException e) {
            logActivity("ADMIN", "LOCK_USER", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public void unlockUserAccount(String username) {
        String sql = "UPDATE users SET locked = FALSE WHERE username = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, username);
            ps.executeUpdate();
            logActivity("ADMIN", "UNLOCK_USER", "SUCCESS", "Username: " + username);
        } catch (SQLException e) {
            logActivity("ADMIN", "UNLOCK_USER", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    public List<User> getAllUsers() {
        List<User> list = new ArrayList<>();
        String sql = "SELECT * FROM users";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                User u = new User();
                u.setId(rs.getLong("id"));
                u.setUsername(rs.getString("username"));
                u.setPassword(rs.getString("password"));
                u.setEmail(rs.getString("email"));
                u.setRole(rs.getString("role"));
                list.add(u);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public boolean isUserLocked(String username) {
        String sql = "SELECT locked FROM users WHERE username = ?";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, username);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return rs.getBoolean("locked");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    public List<Diem> getStudentGrades(String maSV) {
        List<Diem> list = new ArrayList<>();
        String sql = "SELECT d.*, sv.ho_ten, sv.ma_sv AS student_ma_sv, m.ten_mh, m.so_tin_chi, l.ma_lhp " +
                     "FROM diem d JOIN sinh_vien sv ON d.sinh_vien_ma_sv = sv.ma_sv " +
                     "JOIN lop_hoc_phan l ON d.lop_hoc_phan_id = l.id " +
                     "JOIN mon_hoc m ON l.mon_hoc_ma_mh = m.ma_mh " +
                     "WHERE d.sinh_vien_ma_sv = ? ORDER BY m.ten_mh";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, maSV);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(mapDiemRow(rs));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    private Diem mapDiemRow(ResultSet rs) throws SQLException {
        Diem d = new Diem();
        d.setId(rs.getLong("id"));
        d.setDiemQT(rs.getDouble("diemqt"));
        d.setDiemThi(rs.getDouble("diem_thi"));
        d.setDiemTongKet(rs.getDouble("diem_tong_ket"));
        d.setDiemChu(computeLetterGrade(d.getDiemTongKet()));
        try {
            d.setLocked(rs.getBoolean("locked"));
        } catch (SQLException e) {
            d.setLocked(false);
        }
        SinhVien sv = new SinhVien();
        sv.setMaSV(readString(rs, "student_ma_sv", "sinh_vien_ma_sv", "ma_sv"));
        sv.setHoTen(rs.getString("ho_ten"));
        d.setSinhVien(sv);
        LopHocPhan lhp = new LopHocPhan();
        lhp.setMaLhp(rs.getString("ma_lhp"));
        MonHoc mh = new MonHoc();
        mh.setTenMH(rs.getString("ten_mh"));
        mh.setSoTinChi(rs.getInt("so_tin_chi"));
        lhp.setMonHoc(mh);
        d.setLopHocPhan(lhp);
        return d;
    }

    private String readString(ResultSet rs, String... columns) {
        for (String column : columns) {
            try {
                String value = rs.getString(column);
                if (value != null && !value.isBlank()) {
                    return value;
                }
            } catch (SQLException ignored) {
                // Try the next candidate column.
            }
        }
        return "";
    }

    public void createFeedback(Feedback fb) {
        String sql = "INSERT INTO phan_hoi (sinh_vien_ma_sv, tieu_de, noi_dung, loai_don, ngay_gui, trang_thai) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, ?)";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, fb.getSinhVien().getMaSV());
            ps.setString(2, fb.getTieuDe());
            ps.setString(3, fb.getNoiDung());
            ps.setString(4, fb.getLoaiDon());
            ps.setString(5, "Chờ xử lý");
            ps.executeUpdate();
            logActivity(fb.getSinhVien().getMaSV(), "CREATE_FEEDBACK", "SUCCESS", "Feedback Title: " + fb.getTieuDe());
        } catch (SQLException e) {
            logActivity(fb.getSinhVien().getMaSV(), "CREATE_FEEDBACK", "FAIL", e.getMessage());
            e.printStackTrace();
        }
    }

    // --- SAMPLE DATA ---
    public void seedSampleDataIfEmpty() {
        com.example.dean12.config.SampleDataGenerator.run();
    }

    public static String computeLetterGrade(double tongKet) {
        if (tongKet >= 8.5) return "A";
        if (tongKet >= 7.0) return "B";
        if (tongKet >= 5.5) return "C";
        if (tongKet >= 4.0) return "D";
        return "F";
    }

    public double[] getStudentGpaSummary(String maSV) {
        List<Diem> grades = getStudentGrades(maSV);
        if (grades.isEmpty()) {
            return new double[]{0, 0, 0};
        }
        double sum = 0;
        int pass = 0;
        for (Diem d : grades) {
            sum += d.getDiemTongKet();
            if (d.getDiemTongKet() >= 4.0) pass++;
        }
        return new double[]{sum / grades.size(), grades.size(), pass};
    }
}
